version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_lovabre
    restart: always
    environment:
      POSTGRES_USER: turbopresell
      POSTGRES_PASSWORD: turbopresell
      POSTGRES_DB: turbopresell
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_lovabre
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres
    networks:
      - postgres_net

volumes:
  pgdata:

networks:
  postgres_net:
    driver: bridge